# Generated by Django 3.1.6 on 2021-02-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20210211_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
